title: DocuMake
description: >
  A Generative Documentation tool written in Kotlin by Calculus Games.

baseurl: ""
url: "https://documake.calcugames.xyz"
github_username: DocuMake

markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass
  sourcemap: always
  quiet_deps: false
  verbose: false